### ISSUE TITLE
카카오톡 광고 삭제 방법 변경

### ISSUE THREAD

**Issue by sokcuri** [RyuaNerin/FucKakaoAd#1]
DLL 바꿔치기 (Proxy DLL)를 사용해서 후킹을 시도하면 별도 프로그램을 켜지 않아도 적용하기 쉬울 것 같아요

**Comment by RyuaNerin** [comment]
코드 공개 이전부터 이미 작업중이였었다고 합니다

**Comment by sokcuri** [comment]
굿굿
