### ISSUE TITLE
Wacapew.C!ml 검출됨

### ISSUE THREAD

**Issue by JUSTIVE** [RyuaNerin/FucKakaoAd#7]
![image](https://user-images.githubusercontent.com/7118300/108306583-d20b2400-71ef-11eb-86f2-e674afcd6bb2.png)

해당 소프트웨어를 사용 중에 윈도우 디펜더에서 다음과 같은 경고가 발생했습니다.

**Comment by RyuaNerin** [comment]
dll injection 을 활용하는 부분때문에 오진하는 것으로 추정됩니다.

https://www.virustotal.com/gui/url/9fff2584ac7d842e8f8b4e0c31284412adb62501631208623118971dafad13ce/detection

**Comment by JUSTIVE** [comment]
답변 감사드립니다
